apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-frontend
  labels:
    app: trend-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend-frontend
  template:
    metadata:
      labels:
        app: trend-frontend
    spec:
      containers:
        - name: trend-frontend
          image: prem18062000/trend-app:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
