apiVersion: v1
kind: Service
metadata:
  name: trend-frontend-lb
spec:
  type: LoadBalancer
  selector:
    app: trend-frontend
  ports:
    - name: http
      port: 3000        # external port
      targetPort: 80    # container port (nginx)
